jobs:
  zscan:
    name: zScan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute gradle build
        run: ./gradlew build

      - name: Run Zimperium zScan
        uses: zimperium/zscanmarketplace@bfc6670f6648d796098c251ccefcfdb98983174d
        timeout-minutes: 60
        with:
          client_env: env_string
          client_id: id_string
          client_secret: ${{ secrets.ZSCAN_CLIENT_SECRET }}
          app_file: app-release-unsigned.apk

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: Zimperium.sarif
